### ISSUE TITLE
Windows server support

### ISSUE THREAD

**Issue by RonXTCdaBass** [alexpsfti/ETDiscord#1]
Hi!

how to run at a win10 powered Server?

in the cmd it loads the script but what then?
i've made a webhook but how to send content from the game to dc webhook?

**Comment by alexpsfti** [comment]
Can you please try this version and let me know ? [https://github.com/alexpsfti/ETDiscord/blob/main/windiscord.lua](https://github.com/alexpsfti/ETDiscord/blob/main/windiscord.lua)

**Comment by RonXTCdaBass** [comment]
> Can you please try this version and let me know ? https://github.com/alexpsfti/ETDiscord/blob/main/windiscord.lua

hello and good morning!
i'm testing

using this script triggered my firewall (the other not) so i addet the cURL thing to my security settings.  

using discord is relative new for me, so please what is to do ?

i've entered my webhook_url into the script line 16 & 21 , changed the flad to :flag_de: and filled my web_mapshots folder...

what is needet more to let it post to my dc?

in the new gamelog i've seen this message:

line 79: `0 Lua 5.4 API: ^$file 'luascripts/windiscord.lua' loaded into Lua VM`

but also

line 308   `10450 Lua 5.4 API: ^$Lua module [luascripts/windiscord.lua] [6B45D2AEC775E52E5D3BC7BB7FC2B067864C6E0D] unloaded.`

and some lines later, this:

```
   10450 ------- Game Initialization -------
   10450 gamename: legacy
   10450 gamedate: Nov 11 2024
   10450 215 cvars in use
   10450 Not logging to disk
   10450 map: rocketbase
   10450 gametype: Map Voting
   10450 gametime: Sun Dec 08 06:26:22 2024
   10450 Lua 5.4 API: ^$file 'luascripts/wolfadmin/main.lua' loaded into Lua VM
   10450 Lua 5.4 API: ^$file 'luascripts/windiscord.lua' loaded into Lua VM
   10450 Enable spawning!
   10450 Disable spawning!
   10450 0 teams with 0 entities
   10450 -----------------------------------
   10450 Setting MOTD...
   10450 GeoIP is enabled. Database memory size: 2100.66 kb
   10450 [WolfAdmin] Module 1.2.1 (14 April 2020) loaded successfully. Created by Timo 'Timothy' Smit.
   10450 [WolfAdmin] WolfAdmin running in standalone mode on windows.
   10450 [WolfAdmin] commands.load(): 0 entries loaded in 141 ms
   10450 [WolfAdmin] WolfAdmin running in standalone mode on windows.
   10450 Lua 5.4 API: ^$et_InitGame error running lua script: '[string "luascripts/windiscord.lua"]:589: attempt to concatenate a nil value (local 'flag')'
   10450 Game Initialization completed in 0.61 seconds
```

i use a "minetest server" at the same pc and the DC plugin have some files more incl. an .exe , some more to enter because it don't use webhook, but this is working.

sorry for my bad english! ;)

**Comment by alexpsfti** [comment]
I've been able to replicate in a VM. Option to show bots is broken.
Can you try: `show_bots = false` please ?
Thanks for testing, haven't had yet the opportunity to run this script on windows.

**Comment by alexpsfti** [comment]
I updated [https://github.com/alexpsfti/ETDiscord/blob/main/windiscord.lua](https://github.com/alexpsfti/ETDiscord/blob/main/windiscord.lua). Can you please try again please ? Thanks.

**Comment by RonXTCdaBass** [comment]
i'm confused...

_ CRYPT_E_NO_REVOCATION_CHECK _

![Clipboard_12-08-2024_01](https://github.com/user-attachments/assets/493f398f-9ab1-40a1-b56f-318fcf8cf456)

but in the "etconsole.log" file it isn't to find...

and still no post in my discord :(

**Comment by alexpsfti** [comment]
I can't replicate. This isn't related to my script.
You have a program (antivirus/antimalware) blocking cURL or a certificate issue on the host.
You can DM me on Discord if you want more help.
[https://discord.com/users/589670337151500308/](https://discord.com/users/589670337151500308/)
